[build]
  publish = "Hackeando_a_Bolsa_de_Valores"  # Certifique-se de que este é o diretório correto para o conteúdo estático
  command = "echo 'No build required'"

[[redirects]]
  from = "/api/*"
  to = "/index.html"
  status = 200
  force = true
